### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by ScripyZz** [Krzmbrzl/Orinoco-SQF#8]
Was wondering if i could add you on discord?

**Comment by Krzmbrzl** [comment]
Well atm we are using a sub-channel on the SQDev-Discord: https://discord.gg/Ny3a4QS
There you'll find the both of us ("K-Town" and "Raven" - the latter one being myself)

As of now there's no dedicated discord server as we figured there wouldn't be a demand for it :)
